version: '3'
services:

  mysql:
    image: "mysql:5.7.30"
    # For MacBook with Apple chips, use the following platform instead.
    # platform: linux/amd64
    ports:
      # Another version of MySQL is installed on the vm and already uses the port 3306.
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  postgres:
    image: "postgres:9.6.18"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  mongodb:
    image: "mongo:4.0.18"
    ports:
      - "27017:27017"

  redis:
    image: "redis:4.0.14"
    ports:
      - "6380:6379"
